language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=10.8

script:
  - wget -q https://github.com/fabianonline/telegram.sh/raw/master/telegram && chmod +x telegram
  - chmod +x sync.sh
  - ./sync.sh
